# Generated by Django 4.0.3 on 2022-03-26 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=500, verbose_name='Summary')),
                ('description', models.TextField(verbose_name='Description')),
                ('high_priority', models.BooleanField(verbose_name='Flag as high priority')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Created'), (1, 'On progress'), (2, 'Completed')], default=0, verbose_name='Status')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated on')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_assigned_requests', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myrequests', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
        ),
    ]
